#!/bin/sh

sudo useradd nrousseau1 && mkdir /home/nrousseau1/.ssh && chown 700 /home/nrousseau1/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvwgaHUhGuH9F1/Wirck6dRFKzIrxv9GkUMZHyRN1aFeNA5QyVuZnQgOaDgEfwvHVOnCks9IRg0jD345wwY0l71hW/ULadCJFMhuz4gslsn/kz36mBT0xDe8E3+04MPqR7XylCVllDYZxtMJk0uwazotFPsyOnPGLJRzAVvuuzQick/Onm4gWBxbtpPeK+V3rGqVIYNC0k4LUwf5OHW0PVL4+4xekHHZ3j3++r6m6WgkpR7foVcIMQH1FkuNmybpCyfLHa5sVC7S16f9e+6EmaxiR8R1MwR7/zlY8AzFxrtEhn6NVhFTeNiQ1QJBGIo5VDhvCCmN/jdrhtpnVYwiswiWCeBIwlAoXdX7zgTGlHN5pmvosuW5OeK1uYHMaq/QlATROQkjMvER5cPF19eaoP8gNtpcxDNLZgjRJ6wbcdQcqbdtyM7kOfgfKkiXn7sji6pYZvg7wQsCtACnYhSKLoYfoXt+bj6TF/lWTsU7/FwgtyneAvtMAFDk39J8xeB8Ly/jxrH0xjNmHR+dP6BkGjW+U7sxIwwnTxc296S60k1QsKM6PZLWRZAqrQktGGlYDGhZxdKP0Yy0+nbf5n2z88f2AlCD4O9Ou2h+gAc0ah5BO5LRj6ULCrdsEk/Dx8TzuPp7MYDamn7TL9KJQrQxt09LsnBY9NDR6etVdLxf30Bw== nrousseau1" > /home/nrousseau1/.ssh/authorized_keys && chmod 600 /home/nrousseau1/.ssh/authorized_keys && chown -R nrousseau1:nrousseau1 /home/nrousseau1
sudo useradd ahedjaz && mkdir /home/ahedjaz/.ssh && chown 700 /home/ahedjaz/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZ8jpyUwBG1xZqjwyNCDNDigPN4k63rzlNwyxB1RhYIgnMw4h9v6NE7AaSwOrS/dcpeGeX5MMlIoBEFOaGUK8yCy7GvzC9JAufw3EQEEr2I0fpovQV5+NULPlzj1q/18d+SA57S1oNkkyUXF71EddTvnVijTMI9XIaqKmGlHele1WmK0z5E9chJrrFymyA3B/61yyg4VdkNslcSFHXBiaVh9CLCxAgE7tRMc52Nd8ZokqHSnl2899ZsCTpBV7xhZ+zsFb6hcrONN7/Icpf0/MwZL6pzpMoKvGQV7EPhNfA+NWzGyvJ5ZInpN8zcyVwVV97TzCAyuD8svmtpCGQy/adx6LMwkmFBOGlC8orGwdFHA9eCvB590l8nCto59D4uUH6YGyXxb6LuYwC/dxssdOD8qfw2Ry+1cQdgcNOGEjoSEtsO1fQvsLaUd2sybG4lFF7pcqqFNlqPNsOnqizMMoTG01oVB+VzFNZW83Mc6cPuHnbn8vK/nRjr4rZf5gRCn/OYifOrk+hLbFoI0JdpXmdOnTk7nZibulnHHWl6/W3KCXWsV0Q1UITXm03Xwh7VsgGxeYu02KCbzNIiyT8Mu3zZw+PJFtWnG/VRpB2kyJDS/onfhhTAHcyjdIppBltwUuvhseeWOBd6RJY2511C3VEstrdoFURA6+Zyb/EYG+oLQ== ali.hedjaz@gfi.fr" > /home/ahedjaz/.ssh/authorized_keys && chmod 600 /home/ahedjaz/.ssh/authorized_keys && chown -R ahedjaz:ahedjaz /home/ahedjaz
sudo useradd mverhegge && mkdir /home/mverhegge/.ssh && chown 700 /home/mverhegge/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAuyCesmbL2KRDGXlSm58gchEQ02jTinV3GEaDiFXTIEq7Nfjh5OCSVMwOT9NYk0XS9QeyiAhcX5WDI63xQDMrNUd6O5ergPUMq6546adDO28+uWHzj9lnwunzf7ueOT76AcDOt+nZ7COD5V7FdReXijgEXJEhJgiHMvybGllEjHUWXl8M4bnNPPP46AoM70pn+8LDgO0GHP1+cSroqv0+vj+VsjndAg3MiW54lW19o3fhwaxj+31HYUKpjwu/4jCo3UCSLYnAhmIV7Odua1wZsgufrTc1nVeg6YXkxbq2a4XicQw4TM6Sk+O3AZcXGqeKzyU4izXYlX8rXZTbLgN5wQ==" > /home/mverhegge/.ssh/authorized_keys && chmod 600 /home/mverhegge/.ssh/authorized_keys && chown -R mverhegge:mverhegge /home/mverhegge
sudo useradd mabbi && mkdir /home/mabbi/.ssh && chown 700 /home/mabbi/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhm/JFfxv7nGafS/gQz7m6bT7nhVhZtl/K/hgrReYV8sMcubq7NOwFk/1MypiHgDxe4ayMPgWzTXmwyGtrKFFQF5QV5ZU2uWQWg7VX9csGprkMDmzqKGjkw1A2SfEnkh1rr84Ft0HlEC02ohKA2wmnocHl2zn1wfYZHdNWCw3bdl18KSO0xmvoHR0xliQ5RATVJKG/i9JaHj0zth4w5y97Q7NfygfmLuiaxK/KXConDYFyHuyx/UGQKu7a9tKVETGudLcRrAgDRsJM13zEGXPaAZDUo3j3RjEg+dbp4Iwp0XLvLBU4aF+y7JZd9uozykE8Q9n8BldfPASBH1b6ml/jQ==" > /home/mabbi/.ssh/authorized_keys && chmod 600 /home/mabbi/.ssh/authorized_keys && chown -R mabbi:mabbi /home/mabbi
sudo useradd mboumati && mkdir /home/mboumati/.ssh && chown 700 /home/mboumati/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtT7UIykBHLCzse6WzpYsecsWJbUtHY/EzDfQfkyCQphPBhuBaTrLIyWQTQbLJYSjusfzwszC+LxOUUpqGkAcduYP8nEWeILP5Wg0axmRJWoWsm963qJhiYWMpjb0smjBVppPDxbQg5Tmg8Lq9n1fSVHwMTBo2MSOFOfqGw8Ht0SSH/dJDVxVGLoezLw+r/XBxmh6QiV7Vhttr6bSSVAGBIoR6j76hrI2PODSpg/g/ThuHkcLtYzcSCX6bHT3HgPlllfAB/sy9tHk+/PM2j/sU8UQ9+BVw3Nlt2jvt0eo3bsSJ9S1y/XxUOlNjLPCOwh4Lj7PGO3js9gwPdvOBpkX4w==" > /home/mboumati/.ssh/authorized_keys && chmod 600 /home/mboumati/.ssh/authorized_keys && chown -R mboumati:mboumati /home/mboumati
sudo useradd tcrouvezier && mkdir /home/tcrouvezier/.ssh && chown 700 /home/tcrouvezier/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAyUEPhN/u2UM5ZFc3Nk7f6U3+uh6hi5DMBcTfjj9ngXyO3bpBmDvpmzMsDxiNkpoRNGJ0Nk4u7r/yfpRJ5OpLePNMT0hozPZmholsbCF9E/+JYaqwH6aXuQ55G2kum9yP6Ds/MDTf4jCle6lFaBneM/KcEOO6u3IxphE2CTvdKV7fNWH4vn9nVglmw2+zS+BiYeDbn8X932C7xBiEj2F7Cx7UVgbUYM4Atkv2hjjlgglIVgN173m0mTB+McCjXF58ajvyk35/yayN6IOE6n8zmGLKaCeeo2mzn0vGFvy7YwxNzGRM7i2h66ZfaER8qApR/iN9wznq8KgU85s89xWExw==" > /home/tcrouvezier/.ssh/authorized_keys && chmod 600 /home/tcrouvezier/.ssh/authorized_keys && chown -R tcrouvezier:tcrouvezier /home/tcrouvezier
sudo useradd mghanem && mkdir /home/mghanem/.ssh && chown 700 /home/mghanem/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAmgZ+Y71mN8yQWrWBCkSxj06MIHUPjT6kw9V514u6bociJwc0TQgi7B80XH2Q6x51313OKeduxsRDN7Au0guj3X6tep5wyR5T3A64bRcwxV5Z0g8M/voLKeb6ixsAodSJyCdipMzUQBRKhhBGXEX8rkHaCoHqL7tTQWWkzzRPMl5LnHjxVH8acfz4TbQLYE6UY6D6M8CnRoEKVNA/YtoZNnkUnWFIMIbib3e/W3X1hivHvoUUnPc4zDfmzHivXeQTG4SZyR23GIJvtZxSPbOlZxN5HonQwhNaSetzUNps2s2NZWdSl58KchcDyVoo0HCMjvVkR+jJ34YdYQBOlzpoaQ==" > /home/mghanem/.ssh/authorized_keys && chmod 600 /home/mghanem/.ssh/authorized_keys && chown -R mghanem:mghanem /home/mghanem
sudo useradd bamri && mkdir /home/bamri/.ssh && chown 700 /home/bamri/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAikqk9ZaCoBxwS9po1twW9a2CCDY7m8s41wJCaJ8jNVaa2D1XCzePYkRaG0pJimCjwEPhZ0AzlFkYileL9oaIOHm/6oIdp+F9As55h3R+9oGS3dCvlIoOOEtP/duq8ZIs6SqrQwsDVX1Uq6KQ17ootYZlBQC+b7JvjwQEzLzGoVpwudY/vqLu446fQ4Aw/vaHQcCeq0uHElEmuTwl8MPJiqTmjaT2KzYOo/RbaT8+YiqqzJc7LY8+PdeO8keFRtumO2w/KXE94fktnFXsUNMalrR8Tnmzs8h11GLTfPMLs8R3ABhhoEhtj7n3JHmIy1xudP5B+F8UjIkEeyOH6YMzlw==" > /home/bamri/.ssh/authorized_keys && chmod 600 /home/bamri/.ssh/authorized_keys && chown -R bamri:bamri /home/bamri
sudo useradd bblondel && mkdir /home/bblondel/.ssh && chown 700 /home/bblondel/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAqbZ6mcvh84uwOTNb6RWTHC/SL+KvabcZcLNQaCCuWbW8/lHxascOZDV/MDzoB3atvmUS9sQtPTbqF4Bwfp/COUBi/H0e7E1vEdom51oqWPwCNcuJqWjjv2IjOiMFhMUq2p0MUH+4J+i8dcnLTmRVMiKxDmuE1ndbdvOGnNGDauy/Y8i2P6ypWuSPO8mEWOH+94pTMLqzdCtXq0udbGJTf/c0Jn3HGA+/FTY373tRfTNNnQIVmbBGEuSNVWpAD/DpI4ZTqr9Q3y7BedBvyZ3sBu0Oh15XceV8g22E4DhBC+KV1rlibg+6DBeYEN3LkkFSLkLeWX8YGCrZ6FuWmdbMdQ==" > /home/bblondel/.ssh/authorized_keys && chmod 600 /home/bblondel/.ssh/authorized_keys && chown -R bblondel:bblondel /home/bblondel
sudo useradd pnorman && mkdir /home/pnorman/.ssh && chown 700 /home/pnorman/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjjfgayXg/oQiWznaKRc2Sb8aAZ4LYBGar5OXAOn2qBQ/D9/RTFHArF7SUaKS2QQVvdTORaFoxco/OQrPfatObD2Tz0HeLhaQTuPpDLWyhb9tWQZ6ms42vy8eJ7P9PKDIMWxhpRcFLXux+X5He0oMfcM1xxfUqjXETb2eFltjqGd/Yq0u+tk23vnLeBo92Z30srfYY5yKhUKtURh1coHm22UATOtUVsXH+l6kNwRx5Ucf8f+aUjkW9TunJ7t6zfeCADbIfEvnrGmMP91BPOwELwJF5s5Y2NCXAqRqKHoCI9Vy0mjPKgItr5kvDKwMElHFs2sotk0yUmbc2bAOoxV52w==" > /home/pnorman/.ssh/authorized_keys && chmod 600 /home/pnorman/.ssh/authorized_keys && chown -R pnorman:pnorman /home/pnorman
sudo useradd rvandierdonck && mkdir /home/rvandierdonck/.ssh && chown 700 /home/rvandierdonck/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkoF359UzHmot+o6azoqrlwqDtYxWvEIo3W12S0lku9Rs/Of5fT6WJD/+Qn5iREXEQKa4bjiiKcBYXoJyZPx5OZvTfGTZDcNyfbjDiH+DrnB5K9zfT7LB+ybrSPeZWq/OgL9cnhTKS0kTDd0VCYCcEM3hZyKz0S1lIQqlcpjDk8ifiYktaLy2OLkcDdOvzMcrOPwGsVN+veBWeO6PXSkOwFKWi+THP9sPOD0Hh/M2V8zDCnOt3D1kHIRQQGwnil69bo/TunJ2uEZ8sol16+lVAyqW5Ih1rMJgmGnJDv+JhalBJUy9i87pCUPlOpw71LjGoSjThtVqHvwbfO2ywNu7dQ==" > /home/rvandierdonck/.ssh/authorized_keys && chmod 600 /home/rvandierdonck/.ssh/authorized_keys && chown -R rvandierdonck:rvandierdonck /home/rvandierdonck

sudo amazon-linux-extras install epel
sudo yum update -y
sudo yum install nginx -y

sudo systemctl enable nginx

sudo systemctl start nginx

sudo aws s3 cp s3://mutex-configuration/nginx/tomcat1.conf /etc/nginx/default.d/tomcat1.conf
sudo aws s3 cp s3://mutex-configuration/nginx/traefik.conf /etc/nginx/default.d/traefik.conf
sudo aws s3 cp s3://mutex-configuration/nginx/nsi.conf /etc/nginx/default.d/nsi.conf
sudo aws s3 cp s3://mutex-configuration/nginx/keycloak.conf /etc/nginx/default.d/keycloak.conf
sudo aws s3 cp s3://mutex-configuration/nginx/ci.conf /etc/nginx/default.d/ci.conf
sudo aws s3 cp s3://mutex-configuration/nginx/nginx.conf /etc/nginx/nginx.conf


sudo mkdir /etc/ssl/private
sudo openssl req -x509 -nodes -days 900 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=FR/ST=Paris/L=Paris/O=Global Security/OU=Nord Mut Department/CN=gfi.Fr"

sudo systemctl reload nginx

